#ifndef __GESTURE_CAR_HEADER_H__
#define __GESTURE_CAR_HEADER_H__

#define CAR_SSID CAR_SSID
#define CAR_PASSWORD CAR_PASSWORD

#define VALUE_LEFT 30
#define VALUE_RIGHT -30
#define VALUE_FORWARD -25
#define VALUE_BACK 25

#endif